// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAby5GkaCY48-K_FAoeKarzfBrZtgewufI',
    appId: '1:707999375534:web:e6b97d01a0c87782df4d3f',
    messagingSenderId: '707999375534',
    projectId: 'expense-tracker-b4351',
    authDomain: 'expense-tracker-b4351.firebaseapp.com',
    storageBucket: 'expense-tracker-b4351.appspot.com',
    measurementId: 'G-KKHYYLBVZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Gz9uA2-TQ5L5tJdIDGdsvFPkF4XAWrg',
    appId: '1:707999375534:android:35a8eb74eeaa84c8df4d3f',
    messagingSenderId: '707999375534',
    projectId: 'expense-tracker-b4351',
    storageBucket: 'expense-tracker-b4351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlhRLqzjvQGm1-O5sMDsosOc_M2Wcf_3I',
    appId: '1:707999375534:ios:66f4c801c89d6556df4d3f',
    messagingSenderId: '707999375534',
    projectId: 'expense-tracker-b4351',
    storageBucket: 'expense-tracker-b4351.appspot.com',
    iosBundleId: 'com.fintrack.expenceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlhRLqzjvQGm1-O5sMDsosOc_M2Wcf_3I',
    appId: '1:707999375534:ios:66f4c801c89d6556df4d3f',
    messagingSenderId: '707999375534',
    projectId: 'expense-tracker-b4351',
    storageBucket: 'expense-tracker-b4351.appspot.com',
    iosBundleId: 'com.fintrack.expenceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAby5GkaCY48-K_FAoeKarzfBrZtgewufI',
    appId: '1:707999375534:web:492042d8298365cfdf4d3f',
    messagingSenderId: '707999375534',
    projectId: 'expense-tracker-b4351',
    authDomain: 'expense-tracker-b4351.firebaseapp.com',
    storageBucket: 'expense-tracker-b4351.appspot.com',
    measurementId: 'G-GTZRRM7P8K',
  );
}
